name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: xvfb-run --auto-servernum lein test
    - name: Cleanup xvfb
      run: |
        xvfb_pids=`ps aux | grep tmp/xvfb-run | grep -v grep | awk '{print $2}'`
        if [ "$xvfb_pids" != "" ]; then
          echo "Killing the following xvfb processes: $xvfb_pids"
          sudo kill $xvfb_pids
        else
          echo "No xvfb processes to kill"
        fi      
      env:
        CI: true
